# Generated by Django 5.2.1 on 2025-05-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Название модели"
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        verbose_name="Максимальная грузоподъемность (тонн)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель самосвала",
                "verbose_name_plural": "Модели самосвалов",
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Бортовой номер",
                    ),
                ),
                (
                    "current_load",
                    models.IntegerField(
                        default=0, verbose_name="Текущий вес груза (тонн)"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trucks",
                        to="trucks.truckmodel",
                        verbose_name="Модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самосвал",
                "verbose_name_plural": "Самосвалы",
            },
        ),
    ]
