[tool.black]
line-length = 79
include = '\.py$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 79
include_trailing_comma = true
lines_after_imports = 2
atomic = false
skip_glob = ["venv/*", ".venv/*", "*/migrations/*"]